name: Deploy Docs

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry>=2.0.0

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --with docs

      - name: Build and deploy
        run: poetry run mkdocs gh-deploy --force
